; STM32F103C8 — OLED + ESP8266 + Buzzer

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.36.5
extra_scripts =
    pre:extra_scripts/u8g2.py
build_flags =
    -I include
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
lib_extra_dirs = lib
